### ISSUE TITLE
Payment CRUD

### ISSUE THREAD

**Issue by ronspeedster** [ronie0B03/portal.acms#1]
## Task

- [x] Payment List UI 
- [x] Create Payment UI
- [x] Read Payment UI 
- [x] Payment Archive List UI 
- [x] Payment List Back End 
- [x] Create Payment Back End 
- [x] Read Payment Back End 
- [x] Update Payment Back End 
- [x] Archive Payment Back End 
- [x] Payment Archive List Back End 
- [x] Payment Restore Back End 
- [x] Payment Delete Back End

**Comment by ronspeedster** [comment]
Member will have to update profile

They then click the tab for payment ledger

They see their amount to be paid and same place may payment instructions na

Then meron din dun
-Date of payment
-Amount paid
-Upload Proof of Payment
Submit

Then they receive a prompt  saying 
Thank you for updating your membership dues. Your payment will be validated and you will receive your Certificate of Good Standing via (email ba or it can be seen also on this platform?)

On our end naman po, when people upload proof of payment, do we receive a notification? 

And then we just click
-Payment Verified where they recieve an acknowledgement

-Issue Certificate of Good Standing

2 steps sana ito just in case they pay pero hindi enough to earn a certificate of good standing
