### ISSUE TITLE
Implement Member Category Feature

### ISSUE THREAD

**Issue by perilloArt3159** [ronie0B03/portal.acms#15]
## Task 

- [x] Add Member Classification Settings for Admin Side navigation
- [x] Create Member Category 
- [x] View Member Category  
- [x] Update Member Category
- [x] Delete Member Category
- [x] Add Status Field in user edit to change membership classification of users 
- [x] List Classifications in Payment Assignment 
- [x]  Assign Payment by Classifications
