### ISSUE TITLE
Verification of Payment (Admin Side)

### ISSUE THREAD

**Issue by ronspeedster** [ronie0B03/portal.acms#2]
## Task 
- [x] User Payment List UI 
- [x] User Payment List Back End
- [x] Payment Verification 
- [x] Change User level Access
