### ISSUE TITLE
Convert to Laravel VueJS SPA

### ISSUE THREAD

**Issue by perilloArt3159** [ronie0B03/portal.acms#22]
## Tasks

- **Setup** 
  
  - [x] Setup Laravel 
  - [ ] Setup VueJs 
  - [ ] Setup Composer Packages 
  - [ ] Setup NPM Packages 

- **Conversion** 
  
  - [x] Convert Database 
  - [ ] Convert Codebase 

- **Backup** 
  
  - [ ] Backup and make script to migrate old data to new Database Structure? 

- **Modules** 
  
  - [ ] Authentication Module 
  - [ ] Payment Module 
  - [ ] Certificate Module 
  - [ ] Member Module
  - [ ] Election Module?
